In [56]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
from pandas.plotting import scatter_matrix
from sklearn import linear_model
from sklearn.model_selection import train_test_split
%matplotlib inline

In [57]:
df = pd.read_csv('Credit.csv', index_col=0)
df = df[df.Limit > 3500]
df['Student'] = df.Student.map({'No':0, 'Yes':1})
df['Married'] = df.Married.map({'No':0, 'Yes':1})
df['Ethnicity'] = df.Ethnicity.map({'Caucasian':0, 'Asian':1, 'African American':2})
df['Female'] = pd.get_dummies(df.Gender)['Female']
df.drop(['Gender'], axis=1, inplace=True)
df.head(3)

,Income,Limit,Rating,Cards,Age,Education,Student,Married,Ethnicity,Balance,Female
1,14.891,3606,283,2,34,11,0,1,0,333,0
2,106.025,6645,483,3,82,15,1,1,1,903,1
3,104.593,7075,514,4,71,11,0,0,1,580,0

In [59]:
y = df.Balance
X =  df[['Rating','Limit','Income','Student']]

In [60]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.33)

In [61]:
model = linear_model.LinearRegression(fit_intercept=True).fit(X_train, y_train)

model.score(X_test, y_test)

In [62]:
model.score(X_test, y_test)

0.99024516911113569

In [64]:
model.intercept_

-724.69405340114406

In [65]:
model.coef_

array([  1.59330687e+00,   2.16173015e-01,  -9.87584036e+00,
         4.92253327e+02])

In [67]:
from itertools import combinations

In [78]:


for i in range(1,11):
    print(list(combinations(['Income', 'Limit', 'Rating', 'Cards', 'Age', 'Education', 'Student',
       'Married', 'Ethnicity', 'Balance', 'Female'],2)))

[('Income', 'Limit'), ('Income', 'Rating'), ('Income', 'Cards'), ('Income', 'Age'), ('Income', 'Education'), ('Income', 'Student'), ('Income', 'Married'), ('Income', 'Ethnicity'), ('Income', 'Balance'), ('Income', 'Female'), ('Limit', 'Rating'), ('Limit', 'Cards'), ('Limit', 'Age'), ('Limit', 'Education'), ('Limit', 'Student'), ('Limit', 'Married'), ('Limit', 'Ethnicity'), ('Limit', 'Balance'), ('Limit', 'Female'), ('Rating', 'Cards'), ('Rating', 'Age'), ('Rating', 'Education'), ('Rating', 'Student'), ('Rating', 'Married'), ('Rating', 'Ethnicity'), ('Rating', 'Balance'), ('Rating', 'Female'), ('Cards', 'Age'), ('Cards', 'Education'), ('Cards', 'Student'), ('Cards', 'Married'), ('Cards', 'Ethnicity'), ('Cards', 'Balance'), ('Cards', 'Female'), ('Age', 'Education'), ('Age', 'Student'), ('Age', 'Married'), ('Age', 'Ethnicity'), ('Age', 'Balance'), ('Age', 'Female'), ('Education', 'Student'), ('Education', 'Married'), ('Education', 'Ethnicity'), ('Education', 'Balance'), ('Education', 'Female'), ('Student', 'Married'), ('Student', 'Ethnicity'), ('Student', 'Balance'), ('Student', 'Female'), ('Married', 'Ethnicity'), ('Married', 'Balance'), ('Married', 'Female'), ('Ethnicity', 'Balance'), ('Ethnicity', 'Female'), ('Balance', 'Female')]
[('Income', 'Limit'), ('Income', 'Rating'), ('Income', 'Cards'), ('Income', 'Age'), ('Income', 'Education'), ('Income', 'Student'), ('Income', 'Married'), ('Income', 'Ethnicity'), ('Income', 'Balance'), ('Income', 'Female'), ('Limit', 'Rating'), ('Limit', 'Cards'), ('Limit', 'Age'), ('Limit', 'Education'), ('Limit', 'Student'), ('Limit', 'Married'), ('Limit', 'Ethnicity'), ('Limit', 'Balance'), ('Limit', 'Female'), ('Rating', 'Cards'), ('Rating', 'Age'), ('Rating', 'Education'), ('Rating', 'Student'), ('Rating', 'Married'), ('Rating', 'Ethnicity'), ('Rating', 'Balance'), ('Rating', 'Female'), ('Cards', 'Age'), ('Cards', 'Education'), ('Cards', 'Student'), ('Cards', 'Married'), ('Cards', 'Ethnicity'), ('Cards', 'Balance'), ('Cards', 'Female'), ('Age', 'Education'), ('Age', 'Student'), ('Age', 'Married'), ('Age', 'Ethnicity'), ('Age', 'Balance'), ('Age', 'Female'), ('Education', 'Student'), ('Education', 'Married'), ('Education', 'Ethnicity'), ('Education', 'Balance'), ('Education', 'Female'), ('Student', 'Married'), ('Student', 'Ethnicity'), ('Student', 'Balance'), ('Student', 'Female'), ('Married', 'Ethnicity'), ('Married', 'Balance'), ('Married', 'Female'), ('Ethnicity', 'Balance'), ('Ethnicity', 'Female'), ('Balance', 'Female')]
[('Income', 'Limit'), ('Income', 'Rating'), ('Income', 'Cards'), ('Income', 'Age'), ('Income', 'Education'), ('Income', 'Student'), ('Income', 'Married'), ('Income', 'Ethnicity'), ('Income', 'Balance'), ('Income', 'Female'), ('Limit', 'Rating'), ('Limit', 'Cards'), ('Limit', 'Age'), ('Limit', 'Education'), ('Limit', 'Student'), ('Limit', 'Married'), ('Limit', 'Ethnicity'), ('Limit', 'Balance'), ('Limit', 'Female'), ('Rating', 'Cards'), ('Rating', 'Age'), ('Rating', 'Education'), ('Rating', 'Student'), ('Rating', 'Married'), ('Rating', 'Ethnicity'), ('Rating', 'Balance'), ('Rating', 'Female'), ('Cards', 'Age'), ('Cards', 'Education'), ('Cards', 'Student'), ('Cards', 'Married'), ('Cards', 'Ethnicity'), ('Cards', 'Balance'), ('Cards', 'Female'), ('Age', 'Education'), ('Age', 'Student'), ('Age', 'Married'), ('Age', 'Ethnicity'), ('Age', 'Balance'), ('Age', 'Female'), ('Education', 'Student'), ('Education', 'Married'), ('Education', 'Ethnicity'), ('Education', 'Balance'), ('Education', 'Female'), ('Student', 'Married'), ('Student', 'Ethnicity'), ('Student', 'Balance'), ('Student', 'Female'), ('Married', 'Ethnicity'), ('Married', 'Balance'), ('Married', 'Female'), ('Ethnicity', 'Balance'), ('Ethnicity', 'Female'), ('Balance', 'Female')]
[('Income', 'Limit'), ('Income', 'Rating'), ('Income', 'Cards'), ('Income', 'Age'), ('Income', 'Education'), ('Income', 'Student'), ('Income', 'Married'), ('Income', 'Ethnicity'), ('Income', 'Balance'), ('Income', 'Female'), ('Limit', 'Rating'), ('Limit', 'Cards'), ('Limit', 'Age'), ('Limit', 'Education'), ('Limit', 'Student'), ('Limit', 'Married'), ('Limit', 'Ethnicity'), ('Limit', 'Balance'), ('Limit', 'Female'), ('Rating', 'Cards'), ('Rating', 'Age'), ('Rating', 'Education'), ('Rating', 'Student'), ('Rating', 'Married'), ('Rating', 'Ethnicity'), ('Rating', 'Balance'), ('Rating', 'Female'), ('Cards', 'Age'), ('Cards', 'Education'), ('Cards', 'Student'), ('Cards', 'Married'), ('Cards', 'Ethnicity'), ('Cards', 'Balance'), ('Cards', 'Female'), ('Age', 'Education'), ('Age', 'Student'), ('Age', 'Married'), ('Age', 'Ethnicity'), ('Age', 'Balance'), ('Age', 'Female'), ('Education', 'Student'), ('Education', 'Married'), ('Education', 'Ethnicity'), ('Education', 'Balance'), ('Education', 'Female'), ('Student', 'Married'), ('Student', 'Ethnicity'), ('Student', 'Balance'), ('Student', 'Female'), ('Married', 'Ethnicity'), ('Married', 'Balance'), ('Married', 'Female'), ('Ethnicity', 'Balance'), ('Ethnicity', 'Female'), ('Balance', 'Female')]
[('Income', 'Limit'), ('Income', 'Rating'), ('Income', 'Cards'), ('Income', 'Age'), ('Income', 'Education'), ('Income', 'Student'), ('Income', 'Married'), ('Income', 'Ethnicity'), ('Income', 'Balance'), ('Income', 'Female'), ('Limit', 'Rating'), ('Limit', 'Cards'), ('Limit', 'Age'), ('Limit', 'Education'), ('Limit', 'Student'), ('Limit', 'Married'), ('Limit', 'Ethnicity'), ('Limit', 'Balance'), ('Limit', 'Female'), ('Rating', 'Cards'), ('Rating', 'Age'), ('Rating', 'Education'), ('Rating', 'Student'), ('Rating', 'Married'), ('Rating', 'Ethnicity'), ('Rating', 'Balance'), ('Rating', 'Female'), ('Cards', 'Age'), ('Cards', 'Education'), ('Cards', 'Student'), ('Cards', 'Married'), ('Cards', 'Ethnicity'), ('Cards', 'Balance'), ('Cards', 'Female'), ('Age', 'Education'), ('Age', 'Student'), ('Age', 'Married'), ('Age', 'Ethnicity'), ('Age', 'Balance'), ('Age', 'Female'), ('Education', 'Student'), ('Education', 'Married'), ('Education', 'Ethnicity'), ('Education', 'Balance'), ('Education', 'Female'), ('Student', 'Married'), ('Student', 'Ethnicity'), ('Student', 'Balance'), ('Student', 'Female'), ('Married', 'Ethnicity'), ('Married', 'Balance'), ('Married', 'Female'), ('Ethnicity', 'Balance'), ('Ethnicity', 'Female'), ('Balance', 'Female')]
[('Income', 'Limit'), ('Income', 'Rating'), ('Income', 'Cards'), ('Income', 'Age'), ('Income', 'Education'), ('Income', 'Student'), ('Income', 'Married'), ('Income', 'Ethnicity'), ('Income', 'Balance'), ('Income', 'Female'), ('Limit', 'Rating'), ('Limit', 'Cards'), ('Limit', 'Age'), ('Limit', 'Education'), ('Limit', 'Student'), ('Limit', 'Married'), ('Limit', 'Ethnicity'), ('Limit', 'Balance'), ('Limit', 'Female'), ('Rating', 'Cards'), ('Rating', 'Age'), ('Rating', 'Education'), ('Rating', 'Student'), ('Rating', 'Married'), ('Rating', 'Ethnicity'), ('Rating', 'Balance'), ('Rating', 'Female'), ('Cards', 'Age'), ('Cards', 'Education'), ('Cards', 'Student'), ('Cards', 'Married'), ('Cards', 'Ethnicity'), ('Cards', 'Balance'), ('Cards', 'Female'), ('Age', 'Education'), ('Age', 'Student'), ('Age', 'Married'), ('Age', 'Ethnicity'), ('Age', 'Balance'), ('Age', 'Female'), ('Education', 'Student'), ('Education', 'Married'), ('Education', 'Ethnicity'), ('Education', 'Balance'), ('Education', 'Female'), ('Student', 'Married'), ('Student', 'Ethnicity'), ('Student', 'Balance'), ('Student', 'Female'), ('Married', 'Ethnicity'), ('Married', 'Balance'), ('Married', 'Female'), ('Ethnicity', 'Balance'), ('Ethnicity', 'Female'), ('Balance', 'Female')]
[('Income', 'Limit'), ('Income', 'Rating'), ('Income', 'Cards'), ('Income', 'Age'), ('Income', 'Education'), ('Income', 'Student'), ('Income', 'Married'), ('Income', 'Ethnicity'), ('Income', 'Balance'), ('Income', 'Female'), ('Limit', 'Rating'), ('Limit', 'Cards'), ('Limit', 'Age'), ('Limit', 'Education'), ('Limit', 'Student'), ('Limit', 'Married'), ('Limit', 'Ethnicity'), ('Limit', 'Balance'), ('Limit', 'Female'), ('Rating', 'Cards'), ('Rating', 'Age'), ('Rating', 'Education'), ('Rating', 'Student'), ('Rating', 'Married'), ('Rating', 'Ethnicity'), ('Rating', 'Balance'), ('Rating', 'Female'), ('Cards', 'Age'), ('Cards', 'Education'), ('Cards', 'Student'), ('Cards', 'Married'), ('Cards', 'Ethnicity'), ('Cards', 'Balance'), ('Cards', 'Female'), ('Age', 'Education'), ('Age', 'Student'), ('Age', 'Married'), ('Age', 'Ethnicity'), ('Age', 'Balance'), ('Age', 'Female'), ('Education', 'Student'), ('Education', 'Married'), ('Education', 'Ethnicity'), ('Education', 'Balance'), ('Education', 'Female'), ('Student', 'Married'), ('Student', 'Ethnicity'), ('Student', 'Balance'), ('Student', 'Female'), ('Married', 'Ethnicity'), ('Married', 'Balance'), ('Married', 'Female'), ('Ethnicity', 'Balance'), ('Ethnicity', 'Female'), ('Balance', 'Female')]
[('Income', 'Limit'), ('Income', 'Rating'), ('Income', 'Cards'), ('Income', 'Age'), ('Income', 'Education'), ('Income', 'Student'), ('Income', 'Married'), ('Income', 'Ethnicity'), ('Income', 'Balance'), ('Income', 'Female'), ('Limit', 'Rating'), ('Limit', 'Cards'), ('Limit', 'Age'), ('Limit', 'Education'), ('Limit', 'Student'), ('Limit', 'Married'), ('Limit', 'Ethnicity'), ('Limit', 'Balance'), ('Limit', 'Female'), ('Rating', 'Cards'), ('Rating', 'Age'), ('Rating', 'Education'), ('Rating', 'Student'), ('Rating', 'Married'), ('Rating', 'Ethnicity'), ('Rating', 'Balance'), ('Rating', 'Female'), ('Cards', 'Age'), ('Cards', 'Education'), ('Cards', 'Student'), ('Cards', 'Married'), ('Cards', 'Ethnicity'), ('Cards', 'Balance'), ('Cards', 'Female'), ('Age', 'Education'), ('Age', 'Student'), ('Age', 'Married'), ('Age', 'Ethnicity'), ('Age', 'Balance'), ('Age', 'Female'), ('Education', 'Student'), ('Education', 'Married'), ('Education', 'Ethnicity'), ('Education', 'Balance'), ('Education', 'Female'), ('Student', 'Married'), ('Student', 'Ethnicity'), ('Student', 'Balance'), ('Student', 'Female'), ('Married', 'Ethnicity'), ('Married', 'Balance'), ('Married', 'Female'), ('Ethnicity', 'Balance'), ('Ethnicity', 'Female'), ('Balance', 'Female')]
[('Income', 'Limit'), ('Income', 'Rating'), ('Income', 'Cards'), ('Income', 'Age'), ('Income', 'Education'), ('Income', 'Student'), ('Income', 'Married'), ('Income', 'Ethnicity'), ('Income', 'Balance'), ('Income', 'Female'), ('Limit', 'Rating'), ('Limit', 'Cards'), ('Limit', 'Age'), ('Limit', 'Education'), ('Limit', 'Student'), ('Limit', 'Married'), ('Limit', 'Ethnicity'), ('Limit', 'Balance'), ('Limit', 'Female'), ('Rating', 'Cards'), ('Rating', 'Age'), ('Rating', 'Education'), ('Rating', 'Student'), ('Rating', 'Married'), ('Rating', 'Ethnicity'), ('Rating', 'Balance'), ('Rating', 'Female'), ('Cards', 'Age'), ('Cards', 'Education'), ('Cards', 'Student'), ('Cards', 'Married'), ('Cards', 'Ethnicity'), ('Cards', 'Balance'), ('Cards', 'Female'), ('Age', 'Education'), ('Age', 'Student'), ('Age', 'Married'), ('Age', 'Ethnicity'), ('Age', 'Balance'), ('Age', 'Female'), ('Education', 'Student'), ('Education', 'Married'), ('Education', 'Ethnicity'), ('Education', 'Balance'), ('Education', 'Female'), ('Student', 'Married'), ('Student', 'Ethnicity'), ('Student', 'Balance'), ('Student', 'Female'), ('Married', 'Ethnicity'), ('Married', 'Balance'), ('Married', 'Female'), ('Ethnicity', 'Balance'), ('Ethnicity', 'Female'), ('Balance', 'Female')]
[('Income', 'Limit'), ('Income', 'Rating'), ('Income', 'Cards'), ('Income', 'Age'), ('Income', 'Education'), ('Income', 'Student'), ('Income', 'Married'), ('Income', 'Ethnicity'), ('Income', 'Balance'), ('Income', 'Female'), ('Limit', 'Rating'), ('Limit', 'Cards'), ('Limit', 'Age'), ('Limit', 'Education'), ('Limit', 'Student'), ('Limit', 'Married'), ('Limit', 'Ethnicity'), ('Limit', 'Balance'), ('Limit', 'Female'), ('Rating', 'Cards'), ('Rating', 'Age'), ('Rating', 'Education'), ('Rating', 'Student'), ('Rating', 'Married'), ('Rating', 'Ethnicity'), ('Rating', 'Balance'), ('Rating', 'Female'), ('Cards', 'Age'), ('Cards', 'Education'), ('Cards', 'Student'), ('Cards', 'Married'), ('Cards', 'Ethnicity'), ('Cards', 'Balance'), ('Cards', 'Female'), ('Age', 'Education'), ('Age', 'Student'), ('Age', 'Married'), ('Age', 'Ethnicity'), ('Age', 'Balance'), ('Age', 'Female'), ('Education', 'Student'), ('Education', 'Married'), ('Education', 'Ethnicity'), ('Education', 'Balance'), ('Education', 'Female'), ('Student', 'Married'), ('Student', 'Ethnicity'), ('Student', 'Balance'), ('Student', 'Female'), ('Married', 'Ethnicity'), ('Married', 'Balance'), ('Married', 'Female'), ('Ethnicity', 'Balance'), ('Ethnicity', 'Female'), ('Balance', 'Female')]

In [79]:
df.columns

Index(['Income', 'Limit', 'Rating', 'Cards', 'Age', 'Education', 'Student',
       'Married', 'Ethnicity', 'Balance', 'Female'],
      dtype='object')

In [83]:
for i in range(1,11):
    combos = list(combinations(['Income', 'Limit', 'Rating', 'Cards', 'Age', 'Education', 'Student',
       'Married', 'Ethnicity', 'Balance', 'Female'],2))
    y = df.Balance
    X =  pd.DataFrame(df, columns=combos)

In [82]:
combos

[('Income', 'Limit'),
 ('Income', 'Rating'),
 ('Income', 'Cards'),
 ('Income', 'Age'),
 ('Income', 'Education'),
 ('Income', 'Student'),
 ('Income', 'Married'),
 ('Income', 'Ethnicity'),
 ('Income', 'Balance'),
 ('Income', 'Female'),
 ('Limit', 'Rating'),
 ('Limit', 'Cards'),
 ('Limit', 'Age'),
 ('Limit', 'Education'),
 ('Limit', 'Student'),
 ('Limit', 'Married'),
 ('Limit', 'Ethnicity'),
 ('Limit', 'Balance'),
 ('Limit', 'Female'),
 ('Rating', 'Cards'),
 ('Rating', 'Age'),
 ('Rating', 'Education'),
 ('Rating', 'Student'),
 ('Rating', 'Married'),
 ('Rating', 'Ethnicity'),
 ('Rating', 'Balance'),
 ('Rating', 'Female'),
 ('Cards', 'Age'),
 ('Cards', 'Education'),
 ('Cards', 'Student'),
 ('Cards', 'Married'),
 ('Cards', 'Ethnicity'),
 ('Cards', 'Balance'),
 ('Cards', 'Female'),
 ('Age', 'Education'),
 ('Age', 'Student'),
 ('Age', 'Married'),
 ('Age', 'Ethnicity'),
 ('Age', 'Balance'),
 ('Age', 'Female'),
 ('Education', 'Student'),
 ('Education', 'Married'),
 ('Education', 'Ethnicity'),
 ('Education', 'Balance'),
 ('Education', 'Female'),
 ('Student', 'Married'),
 ('Student', 'Ethnicity'),
 ('Student', 'Balance'),
 ('Student', 'Female'),
 ('Married', 'Ethnicity'),
 ('Married', 'Balance'),
 ('Married', 'Female'),
 ('Ethnicity', 'Balance'),
 ('Ethnicity', 'Female'),
 ('Balance', 'Female')]

In [94]:
highest_score = 0

for i in range(1,11):
    combos = list(combinations(['Income', 'Limit', 'Rating', 'Cards', 'Age', 'Education', 'Student','Married', 'Ethnicity', 'Female'],i))
    #combos = [[*c] for c in combos]
    
    for com in combos:
        y = df.Balance
        X = pd.DataFrame(df, columns=com)
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
        
        model = linear_model.LinearRegression(fit_intercept=True).fit(X_train, y_train)
        score = model.score(X_test, y_test)
        if highest_score < score:
            highest_score = score
        print('score:', score, 'columns:', com)
        
print ('highest_score:',highest_score)

highest_score: 0.998961124512

In [125]:
highest_score = 0
answer = 'null'
for i in range(1,11):
    combos = list(combinations(['Income', 'Limit', 'Rating', 'Cards', 'Age', 'Education', 'Student','Married', 'Ethnicity', 'Female'],i))
    #combos = [[*c] for c in combos]
    
    for com in combos:
        y = df.Balance
        X = pd.DataFrame(df, columns=com)
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
        
        model = linear_model.LinearRegression(fit_intercept=True).fit(X_train, y_train)
        score = model.score(X_test, y_test)
        if highest_score < score:
            highest_score = score
          
            #columns = print('score:', score, 'columns:', com)
        
            #print ('highest_score:',highest_score, print(com))
print('Highest Score is:',highest_score,com)

Highest Score is: 0.998961124512 ('Income', 'Limit', 'Rating', 'Cards', 'Age', 'Education', 'Student', 'Married', 'Ethnicity', 'Female')

In [126]:
rows = []
for i in range(1,11):
    combos = list(combinations(['Income', 'Limit', 'Rating', 'Cards', 'Age', 'Education', 'Student','Married', 'Ethnicity', 'Female'],i))
    for j,com in enumerate(combos):
        y = df.Balance
        X = pd.DataFrame(df, columns=com)
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
        model = linear_model.LinearRegression(fit_intercept=True).fit(X_train, y_train)
        score = model.score(X_test, y_test)
        s = ', '.join(com)
        rows.append({'Score':score, 'Columns':s, 'Coef':model.coef_,'Int':model.intercept_})
        # print('score:', score, 'columns:', s)
df1 = pd.DataFrame(rows)
df1.head()

                Coef Columns         Int     Score
0    [3.10140736773]  Income  564.006986  0.086668
1   [0.154033096807]   Limit -171.223522  0.537913
2    [2.29397576729]  Rating -254.879310  0.527959
3    [50.7089108911]   Cards  584.296040 -0.023474
4  [-0.434801576922]     Age  758.219638 -0.010028

In [134]:
df1.Score.max()

0.99896112451243235

In [133]:
pd.options.display.max_colwidth = 100

In [135]:
df1

,Coef,Columns,Int,Score
0,[3.10140736773],Income,564.006986,0.086668
1,[0.154033096807],Limit,-171.223522,0.537913
2,[2.29397576729],Rating,-254.879310,0.527959
3,[50.7089108911],Cards,584.296040,-0.023474
4,[-0.434801576922],Age,758.219638,-0.010028
5,[1.62703707626],Education,712.849030,-0.005358
6,[471.891203704],Student,692.296296,0.128081
7,[-34.4064619067],Married,755.782609,0.001615
8,[22.7357159221],Ethnicity,717.470103,-0.006564
9,[59.9402663285],Female,702.722892,-0.031864
10,"[-10.3161520007, 0.326215290725]","Income, Limit",-616.085667,0.785769
11,"[-9.9614774454, 4.72085704789]","Income, Rating",-753.510008,0.785527
12,"[3.01779039098, 46.7118851081]","Income, Cards",430.048303,0.088112
13,"[3.2656087539, -1.78368858946]","Income, Age",651.398487,0.084547
14,"[3.10002457883, 0.535027146198]","Income, Education",556.893294,0.087361
15,"[3.4374300977, 512.201893413]","Income, Student",499.471130,0.164634
16,"[3.13149530239, -46.8072503392]","Income, Married",591.013764,0.096846
17,"[3.08189928153, 10.1059829465]","Income, Ethnicity",557.416093,0.087572
18,"[3.09623660689, 58.3273626608]","Income, Female",533.161821,0.065475
19,"[-0.0945725794934, 3.68014575322]","Limit, Rating",-296.632597,0.517877
20,"[0.151819550117, 30.8390387413]","Limit, Cards",-249.682270,0.558567
21,"[0.158236952628, -2.93818984749]","Limit, Age",-37.104439,0.558409
22,"[0.154022124982, 1.12045965373]","Limit, Education",-186.215955,0.539202
23,"[0.159475967051, 542.388194811]","Limit, Student",-251.989453,0.622003
24,"[0.154204773898, -43.6202637825]","Limit, Married",-145.521946,0.545558
25,"[0.153992505951, 1.54305205172]","Limit, Ethnicity",-172.155082,0.538064
26,"[0.153750004565, 46.3386459183]","Limit, Female",-194.289831,0.527689
27,"[2.26208632786, 19.3023239492]","Rating, Cards",-298.378932,0.539975
28,"[2.35698161453, -2.97698699]","Rating, Age",-121.117986,0.548229
29,"[2.29389863372, 1.43634445448]","Rating, Education",-274.147923,0.529835
...,...,...,...,...
993,"[-9.81619304949, 0.321176094597, 25.0418230468, -0.29393360332, 503.197737463, -4.17051153097, -...","Income, Limit, Cards, Education, Student, Married, Ethnicity, Female",-727.459325,0.997209
994,"[-9.79612378587, 0.324111636367, -1.12924753883, -0.351034790579, 495.833601675, -3.65792081353,...","Income, Limit, Age, Education, Student, Married, Ethnicity, Female",-613.288866,0.991072
995,"[-9.34809426359, 4.65570953396, 2.22764728785, -1.2092272954, 0.608426486301, 475.850109298, -22...","Income, Rating, Cards, Age, Education, Student, Married, Ethnicity",-737.465241,0.979975
996,"[-9.3480598519, 4.65514301637, 2.11681449312, -1.21107755097, 0.645693348602, 474.854341794, -22...","Income, Rating, Cards, Age, Education, Student, Married, Female",-739.609215,0.979810
997,"[-9.36354179738, 4.65734355967, 2.3047007916, -1.2406920917, 0.411788865459, 476.665648773, -0.3...","Income, Rating, Cards, Age, Education, Student, Ethnicity, Female",-748.043043,0.980598
998,"[-9.85813476634, 4.72278821869, -1.53720350846, -1.52786995877, 6.05387679462, -33.3964479215, 1...","Income, Rating, Cards, Age, Education, Married, Ethnicity, Female",-764.941359,0.792469
999,"[-9.34171618787, 4.65399729147, 2.05055072091, -1.20072194798, 476.080591985, -22.1611589357, -0...","Income, Rating, Cards, Age, Student, Married, Ethnicity, Female",-730.705064,0.979547
1000,"[-9.46273746048, 4.65956740702, 1.65832279363, 0.106801114279, 478.348773066, -24.6499707374, -1...","Income, Rating, Cards, Education, Student, Married, Ethnicity, Female",-789.705786,0.977262
1001,"[-9.36418243221, 4.66264682743, -1.20502442915, 0.590572822711, 474.719556055, -22.5803488073, -...","Income, Rating, Age, Education, Student, Married, Ethnicity, Female",-734.903203,0.979404
1002,"[3.54787902951, 49.2095213536, -1.51227921532, -2.57661144575, 519.582141016, -33.8808335108, -1...","Income, Cards, Age, Education, Student, Married, Ethnicity, Female",482.191881,0.136607
1003,"[0.10258207511, 0.874891660076, 29.7025201338, -2.53981606297, -2.27022584017, 545.130049937, -2...","Limit, Rating, Cards, Age, Education, Student, Married, Ethnicity",-181.875573,0.636216
1004,"[0.100096309781, 0.902664420636, 29.1404029555, -2.58387147064, -1.85320927204, 535.137220897, -...","Limit, Rating, Cards, Age, Education, Student, Married, Female",-201.209959,0.642406
1005,"[0.120817209727, 0.602170234931, 31.00494313, -2.58626540216, -2.51259960439, 546.443006235, -20...","Limit, Rating, Cards, Age, Education, Student, Ethnicity, Female",-193.227527,0.636669
1006,"[-0.0466493118321, 3.01550381757, 15.2378572988, -2.9665953188, 3.97692940323, -52.9199997628, 1...","Limit, Rating, Cards, Age, Education, Married, Ethnicity, Female",-221.745253,0.557675
1007,"[0.101229542114, 0.893516891738, 29.5239030298, -2.57487331374, 539.367773392, -31.557117758, -2...","Limit, Rating, Cards, Age, Student, Married, Ethnicity, Female",-215.649814,0.638819
1008,"[0.0997843656565, 0.864960499968, 28.6709778892, -3.37467767588, 550.940863236, -35.7461927448, ...","Limit, Rating, Cards, Education, Student, Married, Ethnicity, Female",-281.918955,0.616273
1009,"[-0.0204230941724, 2.72335900173, -2.50780573756, -2.45989827732, 529.616604955, -39.7213046349,...","Limit, Rating, Age, Education, Student, Married, Ethnicity, Female",-168.498471,0.616347
1010,"[0.161338719289, 33.8368215199, -2.54041763979, -2.27771344483, 547.551765269, -26.8157585413, -...","Limit, Cards, Age, Education, Student, Married, Ethnicity, Female",-170.600651,0.641152
1011,"[2.38950911438, 21.648118181, -2.53213200567, -2.02229656821, 534.046286404, -36.8379288642, -20...","Rating, Cards, Age, Education, Student, Married, Ethnicity, Female",-213.248230,0.625128
1012,"[-9.70071298561, 0.31371858775, 0.10630555706, 25.0423480221, -1.18684079152, 0.208196777847, 50...","Income, Limit, Rating, Cards, Age, Education, Student, Married, Ethnicity",-678.062879,0.998860
1013,"[-9.70255765639, 0.313648700169, 0.106982837109, 24.9200068999, -1.18970951662, 0.256335383817, ...","Income, Limit, Rating, Cards, Age, Education, Student, Married, Female",-680.751984,0.998888
1014,"[-9.70202507749, 0.315264505186, 0.0832973288685, 25.067007343, -1.19072233275, 0.208736213206, ...","Income, Limit, Rating, Cards, Age, Education, Student, Ethnicity, Female",-680.322635,0.998805
1015,"[-10.0815587929, 0.185037325617, 2.0415036472, 11.8079428453, -1.52426831353, 5.9816343296, -21....","Income, Limit, Rating, Cards, Age, Education, Married, Ethnicity, Female",-730.700721,0.801857
1016,"[-9.69705768666, 0.313863226413, 0.10303401684, 24.9193512427, -1.18416160681, 499.796337107, -2...","Income, Limit, Rating, Cards, Age, Student, Married, Ethnicity, Female",-676.558419,0.998800
1017,"[-9.81445202676, 0.314875753504, 0.0932826453775, 24.564162138, -0.284723494754, 502.692014102, ...","Income, Limit, Rating, Cards, Education, Student, Married, Ethnicity, Female",-729.168201,0.997149
1018,"[-9.73209535496, 0.209904609772, 1.67462653653, -1.15458672301, 0.0102455390193, 488.141643523, ...","Income, Limit, Rating, Age, Education, Student, Married, Ethnicity, Female",-665.414179,0.991640
1019,"[-9.70042551289, 0.32084128119, 25.4751152447, -1.1872126739, 0.223656430953, 500.001477687, -2....","Income, Limit, Cards, Age, Education, Student, Married, Ethnicity, Female",-677.746902,0.998866
1020,"[-9.34582942692, 4.65487077167, 2.12219668364, -1.2099554934, 0.634062909049, 475.115215021, -22...","Income, Rating, Cards, Age, Education, Student, Married, Ethnicity, Female",-739.040836,0.979753
1021,"[0.102769874721, 0.87118625004, 29.3626823472, -2.54114244586, -2.18610635809, 542.739385513, -3...","Limit, Rating, Cards, Age, Education, Student, Married, Ethnicity, Female",-187.298683,0.636185
1022,"[-9.69842414909, 0.313728161993, 0.105315079951, 24.9359752086, -1.18757948287, 0.234214460146, ...","Income, Limit, Rating, Cards, Age, Education, Student, Married, Ethnicity, Female",-679.660844,0.998817